# Build stage
FROM node:20-slim as builder

# Define build arguments
ARG VITE_FRONTEND_URL
ARG VITE_FIREBASE_API_KEY
ARG VITE_FIREBASE_AUTH_DOMAIN
ARG VITE_FIREBASE_PROJECT_ID
ARG VITE_FIREBASE_STORAGE_BUCKET
ARG VITE_FIREBASE_MESSAGING_SENDER_ID
ARG VITE_FIREBASE_APP_ID
ARG VITE_FIREBASE_MEASUREMENT_ID
ARG VITE_FIREBASE_FUNCTION_API_URL
ARG VITE_FIREBASE_REGION
ARG VITE_OPENAI_API_KEY
ARG VITE_RECAPTCHA_SITE_KEY
ARG VITE_OPENAI_URL
ARG VITE_OPENAI_MODEL
ARG VITE_EMAILJS_SERVICE_ID
ARG VITE_EMAILJS_TEMPLATE_ID
ARG VITE_EMAILJS_PUBLIC_KEY
ARG VITE_EMAILJS_CUSTOMER_SERVICE_ID
ARG VITE_EMAILJS_CUSTOMER_TEMPLATE_ID
ARG VITE_STRIPE_ENVIRONMENT
ARG VITE_STRIPE_PUBLIC_KEY
ARG VITE_STRIPE_SECRET_KEY
ARG VITE_STRIPE_PLAN_MONTHLY_ID
ARG VITE_STRIPE_PLAN_YEARLY_ID
ARG VITE_STRIPE_PLAN_FAMILY_ID
ARG VITE_STRIPE_PLAN_BASIC_ID
ARG VITE_STRIPE_PLAN_PREMIUM_ID
ARG VITE_JWT_SECRET
ARG VITE_ENCRYPTION_KEY


# Set environment variables from build arguments
ENV VITE_FRONTEND_URL=$VITE_FRONTEND_URL
ENV VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY
ENV VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN
ENV VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID
ENV VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET
ENV VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID
ENV VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID
ENV VITE_FIREBASE_MEASUREMENT_ID=$VITE_FIREBASE_MEASUREMENT_ID
ENV VITE_FIREBASE_FUNCTION_API_URL=$VITE_FIREBASE_FUNCTION_API_URL
ENV VITE_FIREBASE_REGION=$VITE_FIREBASE_REGION
ENV VITE_OPENAI_API_KEY=$VITE_OPENAI_API_KEY
ENV VITE_RECAPTCHA_SITE_KEY=$VITE_RECAPTCHA_SITE_KEY
ENV VITE_OPENAI_URL=$VITE_OPENAI_URL
ENV VITE_OPENAI_MODEL=$VITE_OPENAI_MODEL
ENV VITE_EMAILJS_SERVICE_ID=$VITE_EMAILJS_SERVICE_ID
ENV VITE_EMAILJS_TEMPLATE_ID=$VITE_EMAILJS_TEMPLATE_ID
ENV VITE_EMAILJS_PUBLIC_KEY=$VITE_EMAILJS_PUBLIC_KEY
ENV VITE_EMAILJS_CUSTOMER_SERVICE_ID=$VITE_EMAILJS_CUSTOMER_SERVICE_ID
ENV VITE_EMAILJS_CUSTOMER_TEMPLATE_ID=$VITE_EMAILJS_CUSTOMER_TEMPLATE_ID
ENV VITE_STRIPE_ENVIRONMENT=$VITE_STRIPE_ENVIRONMENT
ENV VITE_STRIPE_PUBLIC_KEY=$VITE_STRIPE_PUBLIC_KEY
ENV VITE_STRIPE_SECRET_KEY=$VITE_STRIPE_SECRET_KEY
ENV VITE_STRIPE_PLAN_MONTHLY_ID=$VITE_STRIPE_PLAN_MONTHLY_ID
ENV VITE_STRIPE_PLAN_YEARLY_ID=$VITE_STRIPE_PLAN_YEARLY_ID
ENV VITE_STRIPE_PLAN_FAMILY_ID=$VITE_STRIPE_PLAN_FAMILY_ID
ENV VITE_STRIPE_PLAN_BASIC_ID=$VITE_STRIPE_PLAN_BASIC_ID
ENV VITE_STRIPE_PLAN_PREMIUM_ID=$VITE_STRIPE_PLAN_PREMIUM_ID
ENV VITE_JWT_SECRET=$VITE_JWT_SECRET
ENV VITE_ENCRYPTION_KEY=$VITE_ENCRYPTION_KEY

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Create .env file during build
RUN echo "VITE_FRONTEND_URL=$VITE_FRONTEND_URL\n\
VITE_FIREBASE_API_KEY=$VITE_FIREBASE_API_KEY\n\
VITE_FIREBASE_AUTH_DOMAIN=$VITE_FIREBASE_AUTH_DOMAIN\n\
VITE_FIREBASE_PROJECT_ID=$VITE_FIREBASE_PROJECT_ID\n\
VITE_FIREBASE_STORAGE_BUCKET=$VITE_FIREBASE_STORAGE_BUCKET\n\
VITE_FIREBASE_MESSAGING_SENDER_ID=$VITE_FIREBASE_MESSAGING_SENDER_ID\n\
VITE_FIREBASE_APP_ID=$VITE_FIREBASE_APP_ID\n\
VITE_FIREBASE_MEASUREMENT_ID=$VITE_FIREBASE_MEASUREMENT_ID\n\
VITE_FIREBASE_FUNCTION_API_URL=$VITE_FIREBASE_FUNCTION_API_URL\n\
VITE_FIREBASE_REGION=$VITE_FIREBASE_REGION\n\
VITE_OPENAI_API_KEY=$VITE_OPENAI_API_KEY\n\
VITE_RECAPTCHA_SITE_KEY=$VITE_RECAPTCHA_SITE_KEY\n\
VITE_OPENAI_URL=$VITE_OPENAI_URL\n\
VITE_OPENAI_MODEL=$VITE_OPENAI_MODEL\n\
VITE_EMAILJS_SERVICE_ID=$VITE_EMAILJS_SERVICE_ID\n\
VITE_EMAILJS_TEMPLATE_ID=$VITE_EMAILJS_TEMPLATE_ID\n\
VITE_EMAILJS_PUBLIC_KEY=$VITE_EMAILJS_PUBLIC_KEY\n\
VITE_EMAILJS_CUSTOMER_SERVICE_ID=$VITE_EMAILJS_CUSTOMER_SERVICE_ID\n\
VITE_EMAILJS_CUSTOMER_TEMPLATE_ID=$VITE_EMAILJS_CUSTOMER_TEMPLATE_ID\n\
VITE_STRIPE_ENVIRONMENT=$VITE_STRIPE_ENVIRONMENT\n\
VITE_STRIPE_PUBLIC_KEY=$VITE_STRIPE_PUBLIC_KEY\n\
VITE_STRIPE_SECRET_KEY=$VITE_STRIPE_SECRET_KEY\n\
VITE_STRIPE_PLAN_MONTHLY_ID=$VITE_STRIPE_PLAN_MONTHLY_ID\n\
VITE_STRIPE_PLAN_YEARLY_ID=$VITE_STRIPE_PLAN_YEARLY_ID\n\
VITE_STRIPE_PLAN_FAMILY_ID=$VITE_STRIPE_PLAN_FAMILY_ID\n\
VITE_STRIPE_PLAN_BASIC_ID=$VITE_STRIPE_PLAN_BASIC_ID\n\
VITE_STRIPE_PLAN_PREMIUM_ID=$VITE_STRIPE_PLAN_PREMIUM_ID\n\
VITE_JWT_SECRET=$VITE_JWT_SECRET\n\
VITE_ENCRYPTION_KEY=$VITE_ENCRYPTION_KEY" > .env

RUN npm run build

# Production stage
FROM nginx:alpine

# Copy the built assets from builder stage
COPY --from=builder /app/dist /usr/share/nginx/html

# Copy nginx configuration
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Create a script to replace environment variables in the JavaScript files
COPY <<EOF /docker-entrypoint.d/40-replace-env-vars.sh
#!/bin/sh

JS_FILES=\$(find /usr/share/nginx/html -type f -name "*.js")

for file in \$JS_FILES; do
  # Replace all environment variables
  envsubst '\
\$VITE_FRONTEND_URL \
\$VITE_FIREBASE_API_KEY \
\$VITE_FIREBASE_AUTH_DOMAIN \
\$VITE_FIREBASE_PROJECT_ID \
\$VITE_FIREBASE_STORAGE_BUCKET \
\$VITE_FIREBASE_MESSAGING_SENDER_ID \
\$VITE_FIREBASE_APP_ID \
\$VITE_FIREBASE_MEASUREMENT_ID \
\$VITE_FIREBASE_FUNCTION_API_URL \
\$VITE_FIREBASE_REGION \
\$VITE_OPENAI_API_KEY \
\$VITE_OPENAI_URL \
\$VITE_OPENAI_MODEL \
\$VITE_EMAILJS_SERVICE_ID \
\$VITE_EMAILJS_TEMPLATE_ID \
\$VITE_EMAILJS_PUBLIC_KEY \
\$VITE_EMAILJS_CUSTOMER_SERVICE_ID \
\$VITE_EMAILJS_CUSTOMER_TEMPLATE_ID \
\$VITE_STRIPE_ENVIRONMENT \
\$VITE_STRIPE_PUBLIC_KEY \
\$VITE_STRIPE_SECRET_KEY \
\$VITE_STRIPE_PLAN_MONTHLY_ID \
\$VITE_STRIPE_PLAN_YEARLY_ID \
\$VITE_STRIPE_PLAN_FAMILY_ID \
\$VITE_STRIPE_PLAN_BASIC_ID \
\$VITE_STRIPE_PLAN_PREMIUM_ID \
\$VITE_RECAPTCHA_SITE_KEY \
\$VITE_JWT_SECRET \
\$VITE_ENCRYPTION_KEY' < \$file > \$file.tmp
  mv \$file.tmp \$file
done
EOF

RUN chmod +x /docker-entrypoint.d/40-replace-env-vars.sh

# Install envsubst
RUN apk add --no-cache gettext

# Expose port 8080 (Cloud Run requirement)
EXPOSE 8080

# Start Nginx
CMD ["nginx", "-g", "daemon off;"] 